### ISSUE TITLE
Problems with virtualenv escape and Ansible 2.2.1

### ISSUE THREAD

**Issue by oneswig** [stackhpc/ansible-role-os-projects#1]
I'm seeing issues when using Ansible-2.2.1 in the virtualenv.
I have Jinja2 2.9.6 inside the virtualenv, which implements the `equalto` test.
Outside the virtualenv, the system has Jinja2 2.7.2, which does not implement the `equalto` test.

What I see is the `os_user` task in `users.yml` fails with this output:

`fatal: [localhost]: FAILED! => 
{
    "failed": true, 
    "msg": "The conditional check '{{ openstack_users |\n   selectattr('name', 'equalto', item.name) |\n   selectattr('enabled') |\n   list |\n   length == 0 }}\n' failed. The error was: no test named 'equalto'\n\nThe error appears to have been in '/home/stack/p3-config/ansible/roles/stackhpc.os-projects/tasks/users.yml': line 26, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Ensure project users exist\n  ^ here\n"
}`

It appears that the version of Jinja2 being picked up is from the system environment rather than the virtualenv we created.

Something curious is that there is no installation of `shade` in the system environment, upon which I believe `os_user` depends.  So `shade` appears to be found in the virtualenv while `Jinja2` is not.

This works as expected if the virtualenv is updated to use Ansible 2.3.1.

**Comment by markgoddard** [comment]
That's odd. It works for me on ilab-gate using a venv with the following installed:

$ pip freeze
ansible==2.2.1.0
asn1crypto==0.22.0
cffi==1.10.0
cryptography==1.8.1
enum34==1.1.6
idna==2.5
ipaddress==1.0.18
Jinja2==2.8.1
MarkupSafe==1.0
packaging==16.8
paramiko==2.1.2
pyasn1==0.2.3
pycparser==2.17
pycrypto==2.6.1
pyparsing==2.2.0
PyYAML==3.12
six==1.10.0

I initially had ansible-2.2.2.0 but reinstalled ansible-2.1.0.0 to test this.

Jinja is only required on the control host, and should be installed in the venv activated in your shell. Shade is required on the target host, in the target venv (p3_venv, by default {{ ansible_env.PWD }}/p3-config-venv).

**Comment by oneswig** [comment]
I just uininstalled Ansible and reinstalled 2.2.1 in my virtualenv and, blow me, it's working again.  That's a pain for all the time wasted investigating, but I think the issue can be put down to some kind of state corruption introduced to the virtualenv.

Arse.
